apiVersion: v1 #kubernetes API version
kind: Service # kubernetes resource kind we're creating
metadata: # metadata for the resource we are creating
  name: cloud-native-k8s-service
spec:
  selector:
    app: cloud-native-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # port service is running on in cluster
      targetPort: 8080 #port exposed by the service
  type: NodePort #type of service